<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ravi" name="wibmo.app.testScripts.AddMoney.AM_023" tests="1" failures="1" timestamp="18 Jun 2017 17:01:27 GMT" time="6.480" errors="0">
  <testcase name="AM_023" time="6.480" classname="wibmo.app.testScripts.AddMoney.AM_023">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at library.Log.info(Log.java:11)
	at wibmo.app.pagerepo.WelcomePage.enterLoginId(WelcomePage.java:179)
	at wibmo.app.pagerepo.WelcomePage.selectUser(WelcomePage.java:163)
	at wibmo.app.testScripts.AddMoney.AM_023.AM_023(AM_023.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(Unknown Source)
	at com.relevantcodes.extentreports.Report.setFilePath(Report.java:523)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:79)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:374)
	at library.ExtentManager.getReporter(ExtentManager.java:57)
	at library.ExtentTestManager.<clinit>(ExtentTestManager.java:11)
	... 28 more
]]>
    </failure>
  </testcase> <!-- AM_023 -->
</testsuite> <!-- wibmo.app.testScripts.AddMoney.AM_023 -->
